[build]
  publish = "dist/mindmate-frontend"
  command = "ng build --configuration production"

# Environment variable processing during build
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--legacy-peer-deps"

# Redirect all routes to index.html for Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the backend when deployed separately
[[redirects]]
  from = "/api/*"
  to = "https://mindmate-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
