[build]
  publish = "dist/mindmate-frontend"
  command = "ng build --configuration production"

# Redirect all routes to index.html for Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the backend when deployed separately
[[redirects]]
  from = "/api/*"
  to = "https://mindmate-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
